package com.apifacturacion.rest.controler;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
//import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
//import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import com.apifacturacion.rest.modelo.Persona;
import com.apifacturacion.rest.repositorio.PersonaRepo;

@Controller // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class ControlerPersona {
	
	@Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
	private PersonaRepo personRepository;

	/*	@PostMapping(path="/add") // Map ONLY POST Requests
	public @ResponseBody String addNewUser (@RequestParam String name,@RequestParam String email) {		
	// @ResponseBody means the returned String is the response, not a view name
	// @RequestParam means it is a parameter from the GET or POST request

		Persona n = new Persona();
		n.setName(name);
		n.setEmail(email);
		personRepository.save(n);
		return "Saved";
	}*/
	
	@PostMapping(path="/add")
	public @ResponseBody void insertar(@RequestBody Persona per) {
		personRepository.save(per);
		//return "Ha sido creado con éxtito";
	}

	@GetMapping(path="/all")
	public @ResponseBody Iterable<Persona> getAllUsers() {
		// This returns a JSON or XML with the users
		return personRepository.findAll();
	}
		
}
